version: 2
jobs:
  build:
    working_directory: ~/unravel
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: clojure
      - run: boot -d org.clojure/clojure:1.9.0-alpha17 show --deps
      - save_cache:
          paths:
            - ~/.m2
          key: clojure
      - run: node --version
