#!/usr/bin/env bash

set -euo pipefail

make_command() {
    cmd="(do (require 'clojure.core.server) (let [srv (clojure.core.server/start-server {:name :repl :port 0 :accept 'clojure.core.server/repl :server-daemon false})] (println (str \\newline (pr-str [:jack-in/ready {:method :${1}, :port (.getLocalPort srv)}])))))"
}


if [[ -e build.boot ]]; then
    make_command boot
    exec boot -i "$cmd" wait
elif [[ -e project.clj ]]; then
    make_command lein
    exec lein trampoline run -m clojure.main -e "$cmd"
else
    make_command clj
    exec clj -e "$cmd"
fi
